name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install corepack
        run: npm install -g corepack
      - name: Install package manager
        run: corepack install

      - name: Install Dependencies
        run: corepack pnpm install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: corepack pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
